# -*- coding: utf-8 -*-
<<<<<<< HEAD
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
=======
# Generated by Django 1.9 on 2017-09-04 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10


class Migration(migrations.Migration):

<<<<<<< HEAD
=======
    initial = True

>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('food_type', models.CharField(max_length=30)),
                ('main_picture', models.ImageField(upload_to='dishes_picture', blank=True)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('food_type', models.CharField(max_length=30)),
                ('main_picture', models.ImageField(blank=True, upload_to='dishes_picture')),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
            ],
        ),
        migrations.CreateModel(
            name='Order_records',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
                ('quantity', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('cruisine', models.CharField(max_length=30)),
                ('restaurant_logo', models.ImageField(upload_to='restaurant_logo', blank=True)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('cruisine', models.CharField(max_length=30)),
                ('restaurant_logo', models.ImageField(blank=True, upload_to='restaurant_logo')),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_icon', models.FileField(default='WhatEater_Small.jpeg', upload_to='user_icon', blank=True)),
                ('user_footprint', models.IntegerField(default=0)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_icon', models.FileField(blank=True, default='WhatEater_Small.jpeg', upload_to='user_icon')),
                ('user_footprint', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
            ],
        ),
        migrations.AddField(
            model_name='order_records',
            name='order_restaurant',
<<<<<<< HEAD
            field=models.ForeignKey(to='home.Restaurant'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Restaurant'),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
        ),
        migrations.AddField(
            model_name='order_records',
            name='order_user',
<<<<<<< HEAD
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
        ),
        migrations.AddField(
            model_name='order_records',
            name='wanted_dish',
<<<<<<< HEAD
            field=models.ForeignKey(to='home.Dishes'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Dishes'),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
        ),
        migrations.AddField(
            model_name='dishes',
            name='restaurant',
<<<<<<< HEAD
            field=models.ForeignKey(to='home.Restaurant'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Restaurant'),
>>>>>>> e67697016f5eccf4dfc41275c086a7a2f7c2ed10
        ),
    ]
